version: "3.3"
services:
  reverseproxy:
    image: reverseproxy
    build:
      context: ./revese-proxy
      args:
        ENVIRONMENT_NAME: ${ENVIRONMENT_NAME-Production}
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - onyx_network

  api:
    image: 'onyxapi:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME?Variable not set}
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      # Allow explicit env var override for tests
      - CRONTAB="cat crontab"
      - TZ="UTC"
    build:
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    networks:
      - onyx_network

  crontab:
    image: 'crontab_runner:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME?Variable not set}
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      # Allow explicit env var override for tests
      - CRONTAB="cat crontab"
      - TZ="UTC"
    build:
      dockerfile: crontab.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    networks:
      - onyx_network

networks:
  onyx_network:
    driver: bridge