version: "3.3"
services:
  db:
    image: postgres:15
    # volumes:
    #   - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    networks:
      - onyx_network

  api:
    image: 'onyxapi:${TAG-latest}'
    env_file:
      - .env
    environment:
      - SERVER_NAME=${SERVER_NAME?Variable not set}
      - SERVER_HOST=${SERVER_HOST?Variable not set}
      # Allow explicit env var override for tests
      - CRONTAB="cat crontab"
      - TZ="UTC"
    volumes:
      - ./src/:/app
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    command: sh -c "while :; do sleep 1; done"
    depends_on:
      - db
    networks:
      - onyx_network
  
  seq_logs:
    image: datalust/seq:latest
    ports:
      - "80:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=https://localhost
      - SEQ_FIRSTRUN_ADMINPASSWORDHASH=QG9cIOpv29JqzfeKpieAiaGY2AjUikUvIqRd4nUoh313bv9z6WArF55fF4DYKDxkoM5dC2MqfDYG8MQcmU+uuCC7kgKg0KGtKkcHxmAqM/X6
    networks:
      - onyx_network


networks:
  onyx_network:
    driver: bridge

volumes:
  app-db-data: