on:
  push:
    branches:
      - main
      - develop
name: Linux_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: "Checkout GitHub Action"
        uses: actions/checkout@main

      - name: "List directory contents"
        run: ls -R

      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            ENVIRONMENT_NAME=Production
          else
            ENVIRONMENT_NAME=Development
          fi
          docker build . --file ./reverse-proxy/Dockerfile --build-arg ENVIRONMENT_NAME=$ENVIRONMENT_NAME -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/reverse_proxy:${{ github.run_number }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/reverse_proxy:${{ github.run_number }}
